# cargo-about configuration for THIRD_PARTY_NOTICES.md (see scripts/third-party-notices.mjs).
# A crate with a licence outside this list fails generation until the licence is reviewed.
accepted = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
targets = ["x86_64-unknown-linux-gnu"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
